// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVttLGaAuq57VMTWR_6UrL0yIiZadwcY',
    appId: '1:799474908487:web:6fe3852249b51e98a96062',
    messagingSenderId: '799474908487',
    projectId: 'cropi-399723',
    authDomain: 'cropi-399723.firebaseapp.com',
    storageBucket: 'cropi-399723.appspot.com',
    measurementId: 'G-XSCH3VRE51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFkX5tze37GC90FncqG4IH-1h380iYdF8',
    appId: '1:799474908487:android:5ba8b13a97aca4e8a96062',
    messagingSenderId: '799474908487',
    projectId: 'cropi-399723',
    storageBucket: 'cropi-399723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTcp6z7a6JP33rrS8SRASw9YDy5M6c2GM',
    appId: '1:799474908487:ios:9ce02340f9478642a96062',
    messagingSenderId: '799474908487',
    projectId: 'cropi-399723',
    storageBucket: 'cropi-399723.appspot.com',
    iosBundleId: 'dev.brolese.cropi',
  );
}
